const photosTypes = {
  GET_PHOTOS: "GET_PHOTOS",
  GET_PHOTOS_START: "GET_PHOTOS_START",
  GET_PHOTOS_SUCCESS: "GET_PHOTOS_SUCCESS",
  GET_PHOTOS_FAIL: "GET_PHOTOS_FAIL",

  GET_TOPICS: "GET_TOPICS",
  GET_TOPICS_START: "GET_TOPICS_START",
  GET_TOPICS_SUCCESS: "GET_TOPICS_SUCCESS",
  GET_TOPICS_FAIL: "GET_TOPICS_FAIL",
};

export default photosTypes;
